export const ESPECIES_INSS = [
  {
    codigo: "01",
    descricao: "Pensão por Morte de Trabalhador Rural",
    especie: "01 - Pensão por Morte de Trabalhador Rural",
  },
  {
    codigo: "02",
    descricao: "Pensão por Morte Acidentária Trabalhador Rural",
    especie: "02 - Pensão por Morte Acidentária Trabalhador Rural",
  },
  {
    codigo: "03",
    descricao: "Pensão por Morte de Empregador Rural",
    especie: "03 - Pensão por Morte de Empregador Rural",
  },
  {
    codigo: "04",
    descricao: "Aposentadoria por Invalidez Trabalhador Rural",
    especie: "04 - Aposentadoria por Invalidez Trabalhador Rural",
  },
  {
    codigo: "05",
    descricao: "Aposentadoria Invalidez Acidentária Trabalhador Rural",
    especie: "05 - Aposentadoria Invalidez Acidentária Trabalhador Rural",
  },
  {
    codigo: "06",
    descricao: "Aposentadoria Invalidez Empregador Rural",
    especie: "06 - Aposentadoria Invalidez Empregador Rural",
  },
  {
    codigo: "07",
    descricao: "Aposentadoria por Velhice Trabalhador Rural",
    especie: "07 - Aposentadoria por Velhice Trabalhador Rural",
  },
  {
    codigo: "08",
    descricao: "Aposentadoria por Idade Empregador Rural",
    especie: "08 - Aposentadoria por Idade Empregador Rural",
  },
  {
    codigo: "09",
    descricao: "Compl. Acidente Trabalho p/Trabalhador (rural)",
    especie: "09 - Compl. Acidente Trabalho p/Trabalhador (rural)",
  },
  {
    codigo: "10",
    descricao: "Auxílio Doença Acidentário Trabalhador Rural",
    especie: "10 - Auxílio Doença Acidentário Trabalhador Rural",
  },
  {
    codigo: "11",
    descricao: "Amparo Previdenc. Invalidez Trabalhador Rural",
    especie: "11 - Amparo Previdenc. Invalidez Trabalhador Rural",
  },
  {
    codigo: "12",
    descricao: "Amparo Previdenc. Idade Trabalhador Rural",
    especie: "12 - Amparo Previdenc. Idade Trabalhador Rural",
  },
  {
    codigo: "13",
    descricao: "Auxílio Doenca Trabalhador Rural",
    especie: "13 - Auxílio Doenca Trabalhador Rural",
  },
  {
    codigo: "15",
    descricao: "Auxílio Reclusão Trabalhador Rural",
    especie: "15 - Auxílio Reclusão Trabalhador Rural",
  },
  {
    codigo: "19",
    descricao: "Pensão de Estudante (lei 7.004/82)",
    especie: "19 - Pensão de Estudante (lei 7.004/82)",
  },
  {
    codigo: "20",
    descricao: "Pensão por Morte de Ex Diplomata",
    especie: "20 - Pensão por Morte de Ex Diplomata",
  },
  {
    codigo: "21",
    descricao: "Pensão por Morte Previdenciária",
    especie: "21 - Pensão por Morte Previdenciária",
  },
  {
    codigo: "22",
    descricao: "Pensão por Morte Estatutária",
    especie: "22 - Pensão por Morte Estatutária",
  },
  {
    codigo: "23",
    descricao: "Pensão por Morte de Ex Combatente",
    especie: "23 - Pensão por Morte de Ex Combatente",
  },
  {
    codigo: "24",
    descricao: "Pensão Especial (ato Institucional)",
    especie: "24 - Pensão Especial (ato Institucional)",
  },
  {
    codigo: "25",
    descricao: "Auxílio Reclusão",
    especie: "25 - Auxílio Reclusão",
  },
  {
    codigo: "26",
    descricao: "Pensão por Morte Especial",
    especie: "26 - Pensão por Morte Especial",
  },
  {
    codigo: "27",
    descricao: "Pensão Morte Servidor Público Federal",
    especie: "27 - Pensão Morte Servidor Público Federal",
  },
  {
    codigo: "28",
    descricao: "Pensão por Morte Regime Geral",
    especie: "28 - Pensão por Morte Regime Geral",
  },
  {
    codigo: "29",
    descricao: "Pensão por Morte Ex Combatente Marítimo",
    especie: "29 - Pensão por Morte Ex Combatente Marítimo",
  },
  {
    codigo: "30",
    descricao: "Renda Mensal Vitalícia por Incapacidade",
    especie: "30 - Renda Mensal Vitalícia por Incapacidade",
  },
  {
    codigo: "31",
    descricao: "Auxílio doença Previdenciário",
    especie: "31 - Auxílio doença Previdenciário",
  },
  {
    codigo: "32",
    descricao: "Aposentadoria Invalidez Previdenciária",
    especie: "32 - Aposentadoria Invalidez Previdenciária",
  },
  {
    codigo: "33",
    descricao: "Aposentadoria Invalidez Aeronauta",
    especie: "33 - Aposentadoria Invalidez Aeronauta",
  },
  {
    codigo: "34",
    descricao: "Aposentadoria Inval. Ex Combatente Marítimo",
    especie: "34 - Aposentadoria Inval. Ex Combatente Marítimo",
  },
  {
    codigo: "35",
    descricao: "Auxílio Doença do Ex Combatente",
    especie: "35 - Auxílio Doença do Ex Combatente",
  },
  {
    codigo: "36",
    descricao: "Auxílio Acidente Previdenciário",
    especie: "36 - Auxílio Acidente Previdenciário",
  },
  {
    codigo: "37",
    descricao: "Aposentadoria Extranumerário Capin",
    especie: "37 - Aposentadoria Extranumerário Capin",
  },
  {
    codigo: "38",
    descricao: "Aposentadoria Extranum. Funcionário Público",
    especie: "38 - Aposentadoria Extranum. Funcionário Público",
  },
  {
    codigo: "39",
    descricao: "Auxílio Invalidez Estudante",
    especie: "39 - Auxílio Invalidez Estudante",
  },
  {
    codigo: "40",
    descricao: "Renda Mensal Vitalícia por Idade",
    especie: "40 - Renda Mensal Vitalícia por Idade",
  },
  {
    codigo: "41",
    descricao: "Aposentadoria por Idade",
    especie: "41 - Aposentadoria por Idade",
  },
  {
    codigo: "42",
    descricao: "Aposentadoria por Tempo de Contribuição",
    especie: "42 - Aposentadoria por Tempo de Contribuição",
  },
  {
    codigo: "43",
    descricao: "Aposentadoria por Tempo Serviço Ex Combatente",
    especie: "43 - Aposentadoria por Tempo Serviço Ex Combatente",
  },
  {
    codigo: "44",
    descricao: "Aposentadoria Especial de Aeronauta",
    especie: "44 - Aposentadoria Especial de Aeronauta",
  },
  {
    codigo: "45",
    descricao: "Aposentadoria Tempo Serviço Jornalista",
    especie: "45 - Aposentadoria Tempo Serviço Jornalista",
  },
  {
    codigo: "46",
    descricao: "Aposentadoria Especial",
    especie: "46 - Aposentadoria Especial",
  },
  {
    codigo: "47",
    descricao: "Abono Permanência em Serviço 35 Anos",
    especie: "47 - Abono Permanência em Serviço 35 Anos",
  },
  {
    codigo: "48",
    descricao: "Abono Permanência em Serviço 30 Anos",
    especie: "48 - Abono Permanência em Serviço 30 Anos",
  },
  {
    codigo: "49",
    descricao: "Aposentadoria Ordinária",
    especie: "49 - Aposentadoria Ordinária",
  },
  {
    codigo: "50",
    descricao: "Auxílio Doença Extinto Plano Básico",
    especie: "50 - Auxílio Doença Extinto Plano Básico",
  },
  {
    codigo: "51",
    descricao: "Aposentadoria Invalidez Extinto Plano Básico",
    especie: "51 - Aposentadoria Invalidez Extinto Plano Básico",
  },
  {
    codigo: "52",
    descricao: "Aposentadoria Idade Extinto Plano Básico",
    especie: "52 - Aposentadoria Idade Extinto Plano Básico",
  },
  {
    codigo: "53",
    descricao: "Auxílio Reclusão Extinto Plano Básico",
    especie: "53 - Auxílio Reclusão Extinto Plano Básico",
  },
  {
    codigo: "54",
    descricao: "Pensão Indenizatória a Cargo da União",
    especie: "54 - Pensão Indenizatória a Cargo da União",
  },
  {
    codigo: "55",
    descricao: "Pensão por Morte Extinto Plano Básico",
    especie: "55 - Pensão por Morte Extinto Plano Básico",
  },
  {
    codigo: "56",
    descricao: "Pensão Vitalícia Sindrome Talidomida",
    especie: "56 - Pensão Vitalícia Sindrome Talidomida",
  },
  {
    codigo: "57",
    descricao: "Aposentadoria Tempo de Serviço de Professor",
    especie: "57 - Aposentadoria Tempo de Serviço de Professor",
  },
  {
    codigo: "58",
    descricao: "Aposentadoria de Anistiados",
    especie: "58 - Aposentadoria de Anistiados",
  },
  {
    codigo: "59",
    descricao: "Pensão por Morte de Anistiados",
    especie: "59 - Pensão por Morte de Anistiados",
  },
  {
    codigo: "60",
    descricao: "Benefício Indenizatório a cargo da União",
    especie: "60 - Benefício Indenizatório a cargo da União",
  },
  {
    codigo: "61",
    descricao: "Auxílio Natalidade",
    especie: "61 - Auxílio Natalidade",
  },
  {
    codigo: "62",
    descricao: "Auxílio Funeral",
    especie: "62 - Auxílio Funeral",
  },
  {
    codigo: "63",
    descricao: "Auxílio Funeral Trabalhador Rural",
    especie: "63 - Auxílio Funeral Trabalhador Rural",
  },
  {
    codigo: "64",
    descricao: "Auxílio Funeral Empregador Rural",
    especie: "64 - Auxílio Funeral Empregador Rural",
  },
  {
    codigo: "65",
    descricao: "Pecúlio Especial Servidor Autárquico",
    especie: "65 - Pecúlio Especial Servidor Autárquico",
  },
  {
    codigo: "66",
    descricao: "Pec. Esp. Servidor Autárquico",
    especie: "66 - Pec. Esp. Servidor Autárquico",
  },
  {
    codigo: "67",
    descricao: "Pecúlio Obrigatório Ex Ipase",
    especie: "67 - Pecúlio Obrigatório Ex Ipase",
  },
  {
    codigo: "68",
    descricao: "Pecúlio Especial de Aposentados",
    especie: "68 - Pecúlio Especial de Aposentados",
  },
  {
    codigo: "69",
    descricao: "Pecúlio de Estudante",
    especie: "69 - Pecúlio de Estudante",
  },
  {
    codigo: "70",
    descricao: "Restituição Contrib. P/Seg. S/Carência",
    especie: "70 - Restituição Contrib. P/Seg. S/Carência",
  },
  {
    codigo: "71",
    descricao: "Salário Família Previdenciário",
    especie: "71 - Salário Família Previdenciário",
  },
  {
    codigo: "72",
    descricao: "Aposentadoria Tempo Serviço Lei de Guerra",
    especie: "72 - Aposentadoria Tempo Serviço Lei de Guerra",
  },
  {
    codigo: "73",
    descricao: "Salário Família Estatutário",
    especie: "73 - Salário Família Estatutário",
  },
  {
    codigo: "74",
    descricao: "Complemento de Pensão a Conta da União",
    especie: "74 - Complemento de Pensão a Conta da União",
  },
  {
    codigo: "75",
    descricao: "Complemento de Aposentadoria a Conta da União",
    especie: "75 - Complemento de Aposentadoria a Conta da União",
  },
  {
    codigo: "76",
    descricao: "Salário Família Estatutário",
    especie: "76 - Salário Família Estatutário",
  },
  {
    codigo: "77",
    descricao: "Salário Fam. Estatutário Servidor Sinpas",
    especie: "77 - Salário Fam. Estatutário Servidor Sinpas",
  },
  {
    codigo: "78",
    descricao: "Aposentadoria Idade Lei de Guerra",
    especie: "78 - Aposentadoria Idade Lei de Guerra",
  },
  {
    codigo: "79",
    descricao: "Vantagens de Servidor Aposentado",
    especie: "79 - Vantagens de Servidor Aposentado",
  },
  {
    codigo: "80",
    descricao: "Auxílio Salário Maternidade",
    especie: "80 - Auxílio Salário Maternidade",
  },
  {
    codigo: "81",
    descricao: "Aposentadoria Compulsória Ex Sasse",
    especie: "81 - Aposentadoria Compulsória Ex Sasse",
  },
  {
    codigo: "82",
    descricao: "Aposentadoria Tempo de Serviço Ex Sasse",
    especie: "82 - Aposentadoria Tempo de Serviço Ex Sasse",
  },
  {
    codigo: "83",
    descricao: "Aposentadoria por Invalidez Ex Sasse",
    especie: "83 - Aposentadoria por Invalidez Ex Sasse",
  },
  {
    codigo: "84",
    descricao: "Pensão por Morte Ex Sasse",
    especie: "84 - Pensão por Morte Ex Sasse",
  },
  {
    codigo: "85",
    descricao: "Pensão Vitalícia Seringueiros",
    especie: "85 - Pensão Vitalícia Seringueiros",
  },
  {
    codigo: "86",
    descricao: "Pensão Vitalícia Dependentes Seringueiro",
    especie: "86 - Pensão Vitalícia Dependentes Seringueiro",
  },
  {
    codigo: "87",
    descricao: "Amp. Social Pessoa Portadora Deficiência",
    especie: "87 - Amp. Social Pessoa Portadora Deficiência",
  },
  {
    codigo: "88",
    descricao: "Amparo Social ao Idoso",
    especie: "88 - Amparo Social ao Idoso",
  },
  {
    codigo: "89",
    descricao: "Pensão Esp. Vitimas Hemodiálise Caruaru",
    especie: "89 - Pensão Esp. Vitimas Hemodiálise Caruaru",
  },
  {
    codigo: "90",
    descricao: "Simples Assist. Médica p/ Acidente Trabalhador",
    especie: "90 - Simples Assist. Médica p/ Acidente Trabalhador",
  },
  {
    codigo: "91",
    descricao: "Auxílio Doenca por Acidente do Trabalho",
    especie: "91 - Auxílio Doenca por Acidente do Trabalho",
  },
  {
    codigo: "92",
    descricao: "Aposentadoria Invalidez Acidente Trabalho",
    especie: "92 - Aposentadoria Invalidez Acidente Trabalho",
  },
  {
    codigo: "93",
    descricao: "Pensão por Morte Acidente do Trabalho",
    especie: "93 - Pensão por Morte Acidente do Trabalho",
  },
  {
    codigo: "94",
    descricao: "Auxílio Acidente",
    especie: "94 - Auxílio Acidente",
  },
  {
    codigo: "95",
    descricao: "Auxílio Suplementar Acidente Trabalho",
    especie: "95 - Auxílio Suplementar Acidente Trabalho",
  },
  {
    codigo: "96",
    descricao: "Pensão Especial Hanseníase Lei 11520/07",
    especie: "96 - Pensão Especial Hanseníase Lei 11520/07",
  },
  {
    codigo: "97",
    descricao: "Pecúlio por Morte Acidente do Trabalho",
    especie: "97 - Pecúlio por Morte Acidente do Trabalho",
  },
  {
    codigo: "98",
    descricao: "Abono Anual de Acidente de Trabalho",
    especie: "98 - Abono Anual de Acidente de Trabalho",
  },
  {
    codigo: "99",
    descricao: "Afastamento Até 15 Dias Acidente Trabalhador",
    especie: "99 - Afastamento Até 15 Dias Acidente Trabalhador",
  },
];

export const TIPO_DESPESA = [
  { value: "fixa", label: "FIXA" },
  { value: "variavel", label: "VARIÁVEL" },
];

export const TIPO_LOJA = [
  { value: "matriz", label: "MATRIZ" },
  { value: "filial", label: "FILIAL" },
];

export const NATUREZA_DESPESA = [
  { value: "acessoria_redes_sociais", label: "ACESSORIA REDES SOCIAIS" },
  { value: "agua", label: "ÁGUA" },
  { value: "aluguel", label: "ALUGUEL" },
  { value: "aux_familia", label: "AUXÍLIO FAMÍLIA" },
  { value: "contador", label: "CONTADOR" },
  { value: "conteudo_divulgacao", label: "CONTEÚDO PARA DIVULGAÇÃO" },
  { value: "corretor", label: "CORRETOR(A)" },
  { value: "energia", label: "ENERGIA" },
  { value: "fgts", label: "FGTS" },
  { value: "inss", label: "INSS" },
  { value: "internet", label: "INTERNET" },
  { value: "iptu", label: "IPTU" },
  { value: "plano_telefonico", label: "PLANOS TELEFÔNICOS" },
  { value: "refeicao", label: "REFEIÇÃO" },
  { value: "salario", label: "SALÁRIO" },
  { value: "simples_nacional_nota", label: "SIMPLES NACIONAL (NOTA FISCAL)" },
  { value: "sistema_consulta", label: "SISTEMA DE CONSULTA" },
  { value: "trafego_pago", label: "TRÁFEGO PAGO" },
  { value: "vale_transporte", label: "VALE TRANSPORTE" },
  { value: "outro", label: "OUTRO" },
];

export const SITUACAO_PAGAMENTO = [
  { value: "pago", label: "PAGO" },
  { value: "pendente", label: "PENDENTE" },
];

export const TP_CONVENIO = [
  { value: "FGTS", label: "FGTS" },
  { value: "INSS", label: "INSS" },
  { value: "FEDERAL", label: "FEDERAL" },
  { value: "ESTADO PIAUÍ", label: "ESTADO PIAUÍ" },
  { value: "ESTADO MARANHÃO", label: "ESTADO MARANHÃO" },
  { value: "FORÇAS ARMADAS", label: "FORÇAS ARMADAS" },
  { value: "MARINHA", label: "MARINHA" },
  { value: "AERONÁUTICA", label: "AERONÁUTICA" },
  { value: "PREFEITURA", label: "PREFEITURA" },
  { value: "BPC-LOAS", label: "BPC-LOAS" },
];

export const TP_OPERACAO = [
  { value: "CARTAO BENEFICIO", label: "CARTÃO BENEFÍCIO" },
  { value: "CARTAO CONSIGNADO", label: "CARTÃO CONSIGNADO" },
  { value: "NOVO", label: "NOVO" },
  { value: "NOVO", label: "NOVO (CONTRATO CHEIO)" },
  { value: "PORTABILIDADE", label: "PORTABILIDADE" },
  {
    value: "PORTABILIDADE_REFINANCIAMENTO",
    label: "REFIN. DA PORTABILIDADE",
  },
  { value: "REFINANCIAMENTO", label: "REFINANCIAMENTO" },
  { value: "SAQUE COMPLEMENTAR CARTAO", label: "SAQUE COMPLEMENTAR CARTÃO" },
];

export const UF_OBJECT = [
  { value: "AC", label: "ACRE" },
  { value: "AL", label: "ALAGOAS" },
  { value: "AP", label: "AMAPÁ" },
  { value: "AM", label: "AMAZONAS" },
  { value: "BA", label: "BAHIA" },
  { value: "CE", label: "CEARÁ" },
  { value: "DF", label: "DISTRITO FEDERAL" },
  { value: "ES", label: "ESPÍRITO SANTO" },
  { value: "GO", label: "GOIÁS" },
  { value: "MA", label: "MARANHÃO" },
  { value: "MT", label: "MATO GROSSO" },
  { value: "MS", label: "MATO GROSSO DO SUL" },
  { value: "MG", label: "MINAS GERAIS" },
  { value: "PA", label: "PARÁ" },
  { value: "PB", label: "PARAÍBA" },
  { value: "PR", label: "PARANÁ" },
  { value: "PE", label: "PERNAMBUCO" },
  { value: "PI", label: "PIAUÍ" },
  { value: "RJ", label: "RIO DE JANEIRO" },
  { value: "RN", label: "RIO GRANDE DO NORTE" },
  { value: "RS", label: "RIO GRANDE DO SUL" },
  { value: "RO", label: "RONDÔNIA" },
  { value: "RR", label: "RORAIMA" },
  { value: "SC", label: "SANTA CATARINA" },
  { value: "SP", label: "SÃO PAULO" },
  { value: "SE", label: "SERGIPE" },
  { value: "TO", label: "TOCANTINS" },
];

export const UF_ARRAY = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];

export const ESPECIES_INSS_JSON = {
  10: "10 - Auxílio Doença Acidentário Trabalhador Rural",
  11: "11 - Amparo Previdenc. Invalidez Trabalhador Rural",
  12: "12 - Amparo Previdenc. Idade Trabalhador Rural",
  13: "13 - Auxílio Doenca Trabalhador Rural",
  15: "15 - Auxílio Reclusão Trabalhador Rural",
  19: "19 - Pensão de Estudante (lei 7.004/82)",
  20: "20 - Pensão por Morte de Ex Diplomata",
  21: "21 - Pensão por Morte Previdenciária",
  22: "22 - Pensão por Morte Estatutária",
  23: "23 - Pensão por Morte de Ex Combatente",
  24: "24 - Pensão Especial (ato Institucional)",
  25: "25 - Auxílio Reclusão",
  26: "26 - Pensão por Morte Especial",
  27: "27 - Pensão Morte Servidor Público Federal",
  28: "28 - Pensão por Morte Regime Geral",
  29: "29 - Pensão por Morte Ex Combatente Marítimo",
  30: "30 - Renda Mensal Vitalícia por Incapacidade",
  31: "31 - Auxílio doença Previdenciário",
  32: "32 - Aposentadoria Invalidez Previdenciária",
  33: "33 - Aposentadoria Invalidez Aeronauta",
  34: "34 - Aposentadoria Inval. Ex Combatente Marítimo",
  35: "35 - Auxílio Doença do Ex Combatente",
  36: "36 - Auxílio Acidente Previdenciário",
  37: "37 - Aposentadoria Extranumerário Capin",
  38: "38 - Aposentadoria Extranum. Funcionário Público",
  39: "39 - Auxílio Invalidez Estudante",
  40: "40 - Renda Mensal Vitalícia por Idade",
  41: "41 - Aposentadoria por Idade",
  42: "42 - Aposentadoria por Tempo de Contribuição",
  43: "43 - Aposentadoria por Tempo Serviço Ex Combatente",
  44: "44 - Aposentadoria Especial de Aeronauta",
  45: "45 - Aposentadoria Tempo Serviço Jornalista",
  46: "46 - Aposentadoria Especial",
  47: "47 - Abono Permanência em Serviço 35 Anos",
  48: "48 - Abono Permanência em Serviço 30 Anos",
  49: "49 - Aposentadoria Ordinária",
  50: "50 - Auxílio Doença Extinto Plano Básico",
  51: "51 - Aposentadoria Invalidez Extinto Plano Básico",
  52: "52 - Aposentadoria Idade Extinto Plano Básico",
  53: "53 - Auxílio Reclusão Extinto Plano Básico",
  54: "54 - Pensão Indenizatória a Cargo da União",
  55: "55 - Pensão por Morte Extinto Plano Básico",
  56: "56 - Pensão Vitalícia Sindrome Talidomida",
  57: "57 - Aposentadoria Tempo de Serviço de Professor",
  58: "58 - Aposentadoria de Anistiados",
  59: "59 - Pensão por Morte de Anistiados",
  60: "60 - Benefício Indenizatório a cargo da União",
  61: "61 - Auxílio Natalidade",
  62: "62 - Auxílio Funeral",
  63: "63 - Auxílio Funeral Trabalhador Rural",
  64: "64 - Auxílio Funeral Empregador Rural",
  65: "65 - Pecúlio Especial Servidor Autárquico",
  66: "66 - Pec. Esp. Servidor Autárquico",
  67: "67 - Pecúlio Obrigatório Ex Ipase",
  68: "68 - Pecúlio Especial de Aposentados",
  69: "69 - Pecúlio de Estudante",
  70: "70 - Restituição Contrib. P/Seg. S/Carência",
  71: "71 - Salário Família Previdenciário",
  72: "72 - Aposentadoria Tempo Serviço Lei de Guerra",
  73: "73 - Salário Família Estatutário",
  74: "74 - Complemento de Pensão a Conta da União",
  75: "75 - Complemento de Aposentadoria a Conta da União",
  76: "76 - Salário Família Estatutário",
  77: "77 - Salário Fam. Estatutário Servidor Sinpas",
  78: "78 - Aposentadoria Idade Lei de Guerra",
  79: "79 - Vantagens de Servidor Aposentado",
  80: "80 - Auxílio Salário Maternidade",
  81: "81 - Aposentadoria Compulsória Ex Sasse",
  82: "82 - Aposentadoria Tempo de Serviço Ex Sasse",
  83: "83 - Aposentadoria por Invalidez Ex Sasse",
  84: "84 - Pensão por Morte Ex Sasse",
  85: "85 - Pensão Vitalícia Seringueiros",
  86: "86 - Pensão Vitalícia Dependentes Seringueiro",
  87: "87 - Amp. Social Pessoa Portadora Deficiência",
  88: "88 - Amparo Social ao Idoso",
  89: "89 - Pensão Esp. Vitimas Hemodiálise Caruaru",
  90: "90 - Simples Assist. Médica p/ Acidente Trabalhador",
  91: "91 - Auxílio Doenca por Acidente do Trabalho",
  92: "92 - Aposentadoria Invalidez Acidente Trabalho",
  93: "93 - Pensão por Morte Acidente do Trabalho",
  94: "94 - Auxílio Acidente",
  95: "95 - Auxílio Suplementar Acidente Trabalho",
  96: "96 - Pensão Especial Hanseníase Lei 11520/07",
  97: "97 - Pecúlio por Morte Acidente do Trabalho",
  98: "98 - Abono Anual de Acidente de Trabalho",
  99: "99 - Afastamento Até 15 Dias Acidente Trabalhador",
  "01": "01 - Pensão por Morte de Trabalhador Rural",
  "02": "02 - Pensão por Morte Acidentária Trabalhador Rural",
  "03": "03 - Pensão por Morte de Empregador Rural",
  "04": "04 - Aposentadoria por Invalidez Trabalhador Rural",
  "05": "05 - Aposentadoria Invalidez Acidentária Trabalhador Rural",
  "06": "06 - Aposentadoria Invalidez Empregador Rural",
  "07": "07 - Aposentadoria por Velhice Trabalhador Rural",
  "08": "08 - Aposentadoria por Idade Empregador Rural",
  "09": "09 - Compl. Acidente Trabalho p/Trabalhador (rural)",
  1: "1 - Pensão por Morte de Trabalhador Rural",
  2: "02 - Pensão por Morte Acidentária Trabalhador Rural",
  3: "3 - Pensão por Morte de Empregador Rural",
  4: "4 - Aposentadoria por Invalidez Trabalhador Rural",
  5: "5 - Aposentadoria Invalidez Acidentária Trabalhador Rural",
  6: "6 - Aposentadoria Invalidez Empregador Rural",
  7: "7 - Aposentadoria por Velhice Trabalhador Rural",
  8: "8 - Aposentadoria por Idade Empregador Rural",
  9: "9 - Compl. Acidente Trabalho p/Trabalhador (rural)",
};
